name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Permission
        run: chmod +x ./gradlew

      # Spring Boot 어플리케이션 Build
      - name: Spring Boot Build
        run: ./gradlew clean build --exclude-task test

      # Docker 이미지 Build
      - name: Docker Image Build
        run: docker build -t woosoungcho/findfriend:latest .
        if: runner.os == 'Linux'

      - name: Build ARM Docker Image
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx build --platform linux/arm64 -t woosoungcho/findfriend:latest .
        if: runner.os == 'Linux'

      # DockerHub Login
      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Docker Hub push
      - name: Docker Hub Push
        run: docker push woosoungcho/findfriend:latest

      - name: Connect to WAS & Execute Application
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.WAS_HOST }}
          username: ${{ secrets.WAS_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.WAS_SSH_PORT }}
          script: |
            cd ~/findfriend
            docker-compose down
            docker-compose pull
            docker-compose up -d
